# triada-sec · Red Team profile
name=red
title=Red Team (offensive)
description=Pentesting, exploitation and network auditing tooling.
apt_sources=profiles/red/apt/kali.sources
apt_prefs=profiles/red/apt/kali.pref
package_lists=packages/10-recon.list packages/20-web.list packages/30-network.list
debconf=wireshark-common wireshark-common/install-setuid boolean true
